version: '3'
services:
  rest:
    container_name: REST_APP
    image: 'munirsunchalyaev/rest'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://DATABASE/data
    ports:
      - '9999:9999'
    networks:
      - backend
      - global
    depends_on:
      - postgres

  postgres:
    image: 'postgres'
    container_name: DATABASE
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=data
    networks:
      - backend

  front:
    container_name: FRONTEND
    image: 'nginx'
    ports:
      - '443:80'
    volumes:
      - ${PWD}/src/main/resources/static:/usr/share/nginx/html
    depends_on:
      - rest
    networks:
      - global

networks:
  backend:
  global: